// lib/firebase_options.dart
// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg-K36jPHUCzO5KR-AlBsloNcl9TF4dPA',
    appId: '1:69862723384:android:f648172c2cbc1f240bfbcd',
    messagingSenderId: '69862723384',
    projectId: 'nufitionist-faf66',
    storageBucket: 'nufitionist-faf66.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuUAXF9nMKn_SHHfdotXlZ4Mqx8diiJ7A',
    appId: '1:69862723384:web:149e53a14a5cd3420bfbcd',
    messagingSenderId: '69862723384',
    projectId: 'nufitionist-faf66',
    authDomain: 'nufitionist-faf66.firebaseapp.com',
    storageBucket: 'nufitionist-faf66.firebasestorage.app',
    measurementId: 'G-5M2ZPYMMDC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDek-KaojfT75OurHLWqCYtetLTWKrPDBo',
    appId: '1:69862723384:ios:dd43412004a311da0bfbcd',
    messagingSenderId: '69862723384',
    projectId: 'nufitionist-faf66',
    storageBucket: 'nufitionist-faf66.firebasestorage.app',
    iosBundleId: 'com.example.userOnboarding',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDek-KaojfT75OurHLWqCYtetLTWKrPDBo',
    appId: '1:69862723384:ios:7886f6c1189d3bba0bfbcd',
    messagingSenderId: '69862723384',
    projectId: 'nufitionist-faf66',
    storageBucket: 'nufitionist-faf66.firebasestorage.app',
    iosBundleId: 'com.prowrites.nufitionist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuUAXF9nMKn_SHHfdotXlZ4Mqx8diiJ7A',
    appId: '1:69862723384:web:89c73d4a4e8a74780bfbcd',
    messagingSenderId: '69862723384',
    projectId: 'nufitionist-faf66',
    authDomain: 'nufitionist-faf66.firebaseapp.com',
    storageBucket: 'nufitionist-faf66.firebasestorage.app',
    measurementId: 'G-YRDDJZ4Y8F',
  );
}
